/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5p2_edgarmembreno;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author edgarmembreno
 */
public class MAIN extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearUsuario = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        crear_CEO = new javax.swing.JButton();
        crear_Docente = new javax.swing.JButton();
        crear_Alumno = new javax.swing.JButton();
        crear_Decano = new javax.swing.JButton();
        jd_crearCEO = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nombre_CEO = new javax.swing.JTextField();
        apellido_CEO = new javax.swing.JTextField();
        pregrado_CEO = new javax.swing.JTextField();
        id_CEO = new javax.swing.JTextField();
        experiencia_CEO = new javax.swing.JTextField();
        edad_CEO = new javax.swing.JTextField();
        user_CEO = new javax.swing.JTextField();
        pass_CEO = new javax.swing.JTextField();
        agregar_CEO = new javax.swing.JButton();
        jd_CrearDecano = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        nombre_Decano = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        apellido_Decano = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pregrado_Decano = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        id_Decano = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        edad_Decano = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        user_Decano = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pass_Decano = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        universitario_Decano = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        maestria_Decano = new javax.swing.JTextField();
        agregar_Decano = new javax.swing.JButton();
        jd_CrearDocente = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nombre_Docentes = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        apellido_Docentes = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        pregrado_Docente = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        maestria_Docente = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        alumnos_Docente = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        nombreClase_Docente = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        descripcion_Docente = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        user_Docente = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        pass_Docente = new javax.swing.JTextField();
        Agregar_docente = new javax.swing.JButton();
        jd_CrearAlumno = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        nombre_Alumno = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        apellido_Alumno = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        user_Alumno = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        pass_Alumno = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cuenta_Alumno = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        carrera_Alumno = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        añosCarrera_Alumnos = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        clases_Alumno = new javax.swing.JTextField();
        agregar_Alumnos = new javax.swing.JButton();
        jd_Docente = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Docente = new javax.swing.JList<>();
        jLabel45 = new javax.swing.JLabel();
        Meter_Notas = new javax.swing.JButton();
        jd_Alumno = new javax.swing.JDialog();
        jd_decano = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree_Decano = new javax.swing.JTree();
        jLabel42 = new javax.swing.JLabel();
        jd_CEO = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtree_CEO = new javax.swing.JTree();
        jLabel48 = new javax.swing.JLabel();
        popup = new javax.swing.JPopupMenu();
        eliminar = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        Listar = new javax.swing.JMenuItem();
        jd_ListarAlumno = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_ListaAlumnos = new javax.swing.JTable();
        jLabel44 = new javax.swing.JLabel();
        jd_LisarDocente = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_ListaDocente = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        jd_ModificarAlumno = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList_Modificar = new javax.swing.JList<>();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jd_MeterNotas = new javax.swing.JDialog();
        jLabel46 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        nota_te = new javax.swing.JTextField();
        nota_cooperacion = new javax.swing.JTextField();
        nota_participacion = new javax.swing.JTextField();
        nota_Evaluacion = new javax.swing.JTextField();
        nota_EvaluacionGeneral = new javax.swing.JTextField();
        ingresar_Notas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userMain = new javax.swing.JTextField();
        passMain = new javax.swing.JTextField();
        ingresarSistemas = new javax.swing.JButton();
        crearUsuario = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Crear Cuenta");

        crear_CEO.setText("CEO");
        crear_CEO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_CEOActionPerformed(evt);
            }
        });

        crear_Docente.setText("Docente");
        crear_Docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_DocenteActionPerformed(evt);
            }
        });

        crear_Alumno.setText("Alumnos");
        crear_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_AlumnoActionPerformed(evt);
            }
        });

        crear_Decano.setText("Decano");
        crear_Decano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_DecanoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearUsuarioLayout = new javax.swing.GroupLayout(jd_CrearUsuario.getContentPane());
        jd_CrearUsuario.getContentPane().setLayout(jd_CrearUsuarioLayout);
        jd_CrearUsuarioLayout.setHorizontalGroup(
            jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crear_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3)
                        .addComponent(crear_Alumno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crear_Docente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crear_CEO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jd_CrearUsuarioLayout.setVerticalGroup(
            jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addComponent(crear_CEO)
                .addGap(29, 29, 29)
                .addComponent(crear_Decano)
                .addGap(28, 28, 28)
                .addComponent(crear_Alumno)
                .addGap(38, 38, 38)
                .addComponent(crear_Docente)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("Crear CEO");

        jLabel6.setText("Apellido");

        jLabel7.setText("Titulacion Pregrado");

        jLabel8.setText("ID");

        jLabel9.setText("Años Experiencia");

        jLabel10.setText("Edad");

        jLabel11.setText("User");

        jLabel12.setText("Password");

        agregar_CEO.setText("Crear");
        agregar_CEO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_CEOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearCEOLayout = new javax.swing.GroupLayout(jd_crearCEO.getContentPane());
        jd_crearCEO.getContentPane().setLayout(jd_crearCEOLayout);
        jd_crearCEOLayout.setHorizontalGroup(
            jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearCEOLayout.createSequentialGroup()
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearCEOLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pass_CEO, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(user_CEO)
                            .addComponent(edad_CEO)
                            .addComponent(experiencia_CEO)
                            .addComponent(id_CEO)
                            .addComponent(pregrado_CEO)
                            .addComponent(apellido_CEO)
                            .addComponent(nombre_CEO)))
                    .addGroup(jd_crearCEOLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(342, 342, 342))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearCEOLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jd_crearCEOLayout.setVerticalGroup(
            jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearCEOLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombre_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(apellido_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pregrado_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(id_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(experiencia_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(edad_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(user_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_crearCEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pass_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregar_CEO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel13.setText("Nombre");

        jLabel14.setText("Apellido");

        jLabel15.setText("Titulacion Pregrado");

        jLabel16.setText("ID");

        jLabel17.setText("Edad");

        jLabel18.setText("User");

        jLabel19.setText("Password");

        pass_Decano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_DecanoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel20.setText("Crear Decano");

        jLabel21.setText("Titulo Universitario");

        jLabel22.setText("Titulo de Mestria");

        agregar_Decano.setText("Agregar");
        agregar_Decano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_DecanoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearDecanoLayout = new javax.swing.GroupLayout(jd_CrearDecano.getContentPane());
        jd_CrearDecano.getContentPane().setLayout(jd_CrearDecanoLayout);
        jd_CrearDecanoLayout.setHorizontalGroup(
            jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearDecanoLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_CrearDecanoLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pass_Decano)
                    .addComponent(user_Decano)
                    .addComponent(edad_Decano)
                    .addComponent(id_Decano)
                    .addComponent(pregrado_Decano)
                    .addComponent(apellido_Decano)
                    .addComponent(nombre_Decano, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(universitario_Decano)
                    .addComponent(maestria_Decano))
                .addGap(241, 241, 241))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearDecanoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar_Decano)
                .addGap(136, 136, 136))
        );
        jd_CrearDecanoLayout.setVerticalGroup(
            jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearDecanoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel20)
                .addGap(43, 43, 43)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nombre_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(apellido_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pregrado_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(id_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(edad_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(user_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(pass_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(universitario_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_CrearDecanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(maestria_Decano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(agregar_Decano)
                .addGap(22, 22, 22))
        );

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel23.setText("Crear Docente");

        jLabel24.setText("Nombre");

        jLabel25.setText("Apellido");

        jLabel26.setText("Titulacion Pregrado");

        jLabel27.setText("Mestria");

        jLabel28.setText("Cantidad de Alumnos");

        jLabel29.setText("Nombre de Clase");

        jLabel30.setText("Descripcion");

        jLabel31.setText("User");

        jLabel32.setText("Password");

        pass_Docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_DocenteActionPerformed(evt);
            }
        });

        Agregar_docente.setText("Agregar");
        Agregar_docente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_docenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearDocenteLayout = new javax.swing.GroupLayout(jd_CrearDocente.getContentPane());
        jd_CrearDocente.getContentPane().setLayout(jd_CrearDocenteLayout);
        jd_CrearDocenteLayout.setHorizontalGroup(
            jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearDocenteLayout.createSequentialGroup()
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearDocenteLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel23)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearDocenteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_CrearDocenteLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombre_Docentes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearDocenteLayout.createSequentialGroup()
                                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_CrearDocenteLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(alumnos_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_CrearDocenteLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(user_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(apellido_Docentes, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                .addComponent(pregrado_Docente)
                                                .addComponent(maestria_Docente)
                                                .addComponent(nombreClase_Docente)
                                                .addComponent(descripcion_Docente))))))
                            .addGroup(jd_CrearDocenteLayout.createSequentialGroup()
                                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pass_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearDocenteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Agregar_docente)
                .addGap(176, 176, 176))
        );
        jd_CrearDocenteLayout.setVerticalGroup(
            jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearDocenteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel23)
                .addGap(79, 79, 79)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(nombre_Docentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(apellido_Docentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(pregrado_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(maestria_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(alumnos_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(nombreClase_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(descripcion_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(user_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(pass_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Agregar_docente)
                .addGap(26, 26, 26))
        );

        jLabel33.setText("Nombre");

        jLabel34.setText("Apellido");

        jLabel35.setText("User");

        user_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_AlumnoActionPerformed(evt);
            }
        });

        jLabel36.setText("Password");

        pass_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_AlumnoActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel37.setText("Crear Alumnos");

        jLabel38.setText("No. Cuenta");

        jLabel39.setText("Carrera");

        jLabel40.setText("Año Carrera");

        jLabel41.setText("Clases Faltantes");

        agregar_Alumnos.setText("Agregar");
        agregar_Alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_AlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearAlumnoLayout = new javax.swing.GroupLayout(jd_CrearAlumno.getContentPane());
        jd_CrearAlumno.getContentPane().setLayout(jd_CrearAlumnoLayout);
        jd_CrearAlumnoLayout.setHorizontalGroup(
            jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearAlumnoLayout.createSequentialGroup()
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearAlumnoLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_CrearAlumnoLayout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombre_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_CrearAlumnoLayout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addGap(42, 42, 42)
                                    .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(user_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apellido_Alumno, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearAlumnoLayout.createSequentialGroup()
                                    .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel36)
                                        .addComponent(jLabel38)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel40)
                                        .addComponent(jLabel41))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pass_Alumno, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                        .addComponent(cuenta_Alumno)
                                        .addComponent(carrera_Alumno)
                                        .addComponent(añosCarrera_Alumnos)
                                        .addComponent(clases_Alumno))))))
                    .addGroup(jd_CrearAlumnoLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel37)))
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearAlumnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar_Alumnos)
                .addGap(197, 197, 197))
        );
        jd_CrearAlumnoLayout.setVerticalGroup(
            jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearAlumnoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(nombre_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(apellido_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(user_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(pass_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cuenta_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(carrera_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(añosCarrera_Alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(clases_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(agregar_Alumnos)
                .addGap(43, 43, 43))
        );

        jList_Docente.setModel(new DefaultListModel());
        jList_Docente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_DocenteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_Docente);

        jLabel45.setText("Login Docente");

        Meter_Notas.setText("Meter Notas");
        Meter_Notas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Meter_NotasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_DocenteLayout = new javax.swing.GroupLayout(jd_Docente.getContentPane());
        jd_Docente.getContentPane().setLayout(jd_DocenteLayout);
        jd_DocenteLayout.setHorizontalGroup(
            jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DocenteLayout.createSequentialGroup()
                .addGroup(jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Meter_Notas)
                    .addGroup(jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_DocenteLayout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_DocenteLayout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(jLabel45))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jd_DocenteLayout.setVerticalGroup(
            jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DocenteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel45)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Meter_Notas)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jd_AlumnoLayout = new javax.swing.GroupLayout(jd_Alumno.getContentPane());
        jd_Alumno.getContentPane().setLayout(jd_AlumnoLayout);
        jd_AlumnoLayout.setHorizontalGroup(
            jd_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_AlumnoLayout.setVerticalGroup(
            jd_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Docente");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Alumnos");
        treeNode1.add(treeNode2);
        jtree_Decano.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_Decano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_DecanoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtree_Decano);

        jLabel42.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel42.setText("Portal Decano");

        javax.swing.GroupLayout jd_decanoLayout = new javax.swing.GroupLayout(jd_decano.getContentPane());
        jd_decano.getContentPane().setLayout(jd_decanoLayout);
        jd_decanoLayout.setHorizontalGroup(
            jd_decanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_decanoLayout.createSequentialGroup()
                .addGroup(jd_decanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_decanoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_decanoLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel42)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jd_decanoLayout.setVerticalGroup(
            jd_decanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_decanoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Docente");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Decano");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Alumnos");
        treeNode1.add(treeNode2);
        jtree_CEO.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_CEO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_CEOMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jtree_CEO);

        jLabel48.setText("OPCIONES CEO");

        javax.swing.GroupLayout jd_CEOLayout = new javax.swing.GroupLayout(jd_CEO.getContentPane());
        jd_CEO.getContentPane().setLayout(jd_CEOLayout);
        jd_CEOLayout.setHorizontalGroup(
            jd_CEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CEOLayout.createSequentialGroup()
                .addGroup(jd_CEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CEOLayout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel48))
                    .addGroup(jd_CEOLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jd_CEOLayout.setVerticalGroup(
            jd_CEOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CEOLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel48)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        popup.add(eliminar);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        popup.add(modificar);

        Listar.setText("listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        popup.add(Listar);

        jt_ListaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Carrera", "Cuenta"
            }
        ));
        jScrollPane3.setViewportView(jt_ListaAlumnos);

        jLabel44.setText("Lista de Alumnos");

        javax.swing.GroupLayout jd_ListarAlumnoLayout = new javax.swing.GroupLayout(jd_ListarAlumno.getContentPane());
        jd_ListarAlumno.getContentPane().setLayout(jd_ListarAlumnoLayout);
        jd_ListarAlumnoLayout.setHorizontalGroup(
            jd_ListarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarAlumnoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ListarAlumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addGap(343, 343, 343))
        );
        jd_ListarAlumnoLayout.setVerticalGroup(
            jd_ListarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarAlumnoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel44)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jt_ListaDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Titulo", "Clase"
            }
        ));
        jScrollPane4.setViewportView(jt_ListaDocente);

        jLabel43.setText("Lista de Docentes");

        javax.swing.GroupLayout jd_LisarDocenteLayout = new javax.swing.GroupLayout(jd_LisarDocente.getContentPane());
        jd_LisarDocente.getContentPane().setLayout(jd_LisarDocenteLayout);
        jd_LisarDocenteLayout.setHorizontalGroup(
            jd_LisarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LisarDocenteLayout.createSequentialGroup()
                .addGroup(jd_LisarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_LisarDocenteLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_LisarDocenteLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel43)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jd_LisarDocenteLayout.setVerticalGroup(
            jd_LisarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_LisarDocenteLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jList_Modificar.setModel(new DefaultListModel());
        jList_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_ModificarMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jList_Modificar);

        jLabel47.setText("Modificar");

        jLabel49.setText("Doble click para Modificar");

        javax.swing.GroupLayout jd_ModificarAlumnoLayout = new javax.swing.GroupLayout(jd_ModificarAlumno.getContentPane());
        jd_ModificarAlumno.getContentPane().setLayout(jd_ModificarAlumnoLayout);
        jd_ModificarAlumnoLayout.setHorizontalGroup(
            jd_ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarAlumnoLayout.createSequentialGroup()
                .addGroup(jd_ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ModificarAlumnoLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel47))
                    .addGroup(jd_ModificarAlumnoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ModificarAlumnoLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel49)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jd_ModificarAlumnoLayout.setVerticalGroup(
            jd_ModificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarAlumnoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel47)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel49)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel46.setText("Trabajo en equipo");

        jLabel50.setText("Cooperacion");

        jLabel51.setText("Particupacion");

        jLabel52.setText("Evaluacion");

        jLabel53.setText("Evaluacion General");

        ingresar_Notas.setText("Agregar");

        javax.swing.GroupLayout jd_MeterNotasLayout = new javax.swing.GroupLayout(jd_MeterNotas.getContentPane());
        jd_MeterNotas.getContentPane().setLayout(jd_MeterNotasLayout);
        jd_MeterNotasLayout.setHorizontalGroup(
            jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MeterNotasLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(157, 157, 157)
                .addGroup(jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nota_te)
                        .addComponent(nota_cooperacion)
                        .addComponent(nota_participacion)
                        .addComponent(nota_EvaluacionGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addComponent(nota_Evaluacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MeterNotasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ingresar_Notas)
                .addGap(163, 163, 163))
        );
        jd_MeterNotasLayout.setVerticalGroup(
            jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MeterNotasLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(nota_te, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(nota_cooperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(nota_participacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(nota_Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jd_MeterNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(nota_EvaluacionGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(ingresar_Notas)
                .addGap(72, 72, 72))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setText("User");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Password");

        ingresarSistemas.setText("Ingresar");
        ingresarSistemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarSistemasActionPerformed(evt);
            }
        });

        crearUsuario.setText("Crear Usuario");
        crearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ingresarSistemas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userMain, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                .addComponent(passMain)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(425, 425, 425)
                            .addComponent(crearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(ingresarSistemas)
                .addGap(18, 18, 18)
                .addComponent(crearUsuario)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pass_DecanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_DecanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_DecanoActionPerformed

    private void pass_DocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_DocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_DocenteActionPerformed

    private void pass_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_AlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_AlumnoActionPerformed

    private void user_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_AlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_AlumnoActionPerformed

    private void crear_CEOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_CEOActionPerformed
        jd_crearCEO.setModal(true);
        jd_crearCEO.pack();
        jd_crearCEO.setLocationRelativeTo(this);
        jd_crearCEO.setVisible(true);
    }//GEN-LAST:event_crear_CEOActionPerformed

    private void crear_DecanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_DecanoActionPerformed
        jd_CrearDecano.setModal(true);
        jd_CrearDecano.pack();
        jd_CrearDecano.setLocationRelativeTo(this);
        jd_CrearDecano.setVisible(true);


    }//GEN-LAST:event_crear_DecanoActionPerformed

    private void crear_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_AlumnoActionPerformed
        jd_CrearAlumno.setModal(true);
        jd_CrearAlumno.pack();
        jd_CrearAlumno.setLocationRelativeTo(this);
        jd_CrearAlumno.setVisible(true);
    }//GEN-LAST:event_crear_AlumnoActionPerformed

    private void crear_DocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_DocenteActionPerformed
        jd_CrearDocente.setModal(true);
        jd_CrearDocente.pack();
        jd_CrearDocente.setLocationRelativeTo(this);
        jd_CrearDocente.setVisible(true);

    }//GEN-LAST:event_crear_DocenteActionPerformed

    private void agregar_CEOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_CEOMouseClicked
        try {
            String pregrado = pregrado_CEO.getText();
            int id = Integer.parseInt(id_CEO.getText());
            int experiencia = Integer.parseInt(experiencia_CEO.getText());
            int edad = Integer.parseInt(edad_CEO.getText());
            String nombre = nombre_CEO.getText();
            String apellido = apellido_CEO.getText();
            String user = user_CEO.getText();
            String pass = pass_CEO.getText();

            pregrado_CEO.setText("");
            id_CEO.setText("");
            experiencia_CEO.setText("");
            edad_CEO.setText("");
            nombre_CEO.setText("");
            apellido_CEO.setText("");
            user_CEO.setText("");
            pass_CEO.setText("");

            persona.add(new ceo(pregrado, id, experiencia, edad, nombre, apellido, user, pass));
            ceo.add(new ceo(pregrado, id, experiencia, edad, nombre, apellido, user, pass));
            ceo c = new ceo(pregrado, id, experiencia, edad, nombre, apellido, user, pass);

            DefaultTreeModel m = (DefaultTreeModel) jtree_Decano.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals("CEO")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(c);
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }
            }
            m.reload();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_agregar_CEOMouseClicked

    private void agregar_DecanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_DecanoMouseClicked
        try {
            String pregrado = pregrado_Decano.getText();
            int id = Integer.parseInt(id_Decano.getText());
            int edad = Integer.parseInt(edad_Decano.getText());
            String titulo = universitario_Decano.getText();
            String maestria = maestria_Decano.getText();

            String nombre = nombre_Decano.getText();
            String apellido = apellido_Decano.getText();
            String user = user_Decano.getText();
            String pass = pass_Decano.getText();

            pregrado_Decano.setText("");
            id_Decano.setText("");
            edad_Decano.setText("");
            universitario_Decano.setText("");
            maestria_Decano.setText("");
            nombre_Decano.setText("");
            apellido_Decano.setText("");
            user_Decano.setText("");
            pass_Decano.setText("");

            persona.add(new Decano(pregrado, id, edad, titulo, maestria, nombre, apellido, user, pass));
            decano.add(new Decano(pregrado, id, edad, titulo, maestria, nombre, apellido, user, pass));

            Decano d = new Decano(pregrado, id, edad, titulo, maestria, nombre, apellido, user, pass);

            DefaultTreeModel m = (DefaultTreeModel) jtree_CEO.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals("Decano")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(d);
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }
            }
            m.reload();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_agregar_DecanoMouseClicked

    private void Agregar_docenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_docenteMouseClicked
        try {
            String pregrado = pregrado_Docente.getText();
            String maestria = maestria_Docente.getText();
            int alumnos = (Integer) alumnos_Docente.getValue();
            String clase = nombreClase_Docente.getText();
            String descripcion = descripcion_Docente.getText();

            String nombre = nombre_Docentes.getText();
            String apellido = apellido_Docentes.getText();
            String user = user_Docente.getText();
            String pass = pass_Docente.getText();

            pregrado_Docente.setText("");
            maestria_Docente.setText("");
            nombreClase_Docente.setText("");
            descripcion_Docente.setText("");
            nombre_Docentes.setText("");
            apellido_Docentes.setText("");
            user_Docente.setText("");
            pass_Docente.setText("");

            persona.add(new Docente(pregrado, maestria, alumnos, clase, descripcion, nombre, apellido, user, pass));
            docente.add(new Docente(pregrado, maestria, alumnos, clase, descripcion, nombre, apellido, user, pass));

            Docente d = new Docente(pregrado, maestria, alumnos, clase, descripcion, nombre, apellido, user, pass);

            DefaultTreeModel m = (DefaultTreeModel) jtree_Decano.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals("Docente")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(d);
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }
            }
            m.reload();

            DefaultTreeModel c = (DefaultTreeModel) jtree_CEO.getModel();
            DefaultMutableTreeNode raizz = (DefaultMutableTreeNode) c.getRoot();
            for (int j = 0; j < raizz.getChildCount(); j++) {
                if (raizz.getChildAt(j).toString().equals("Docente")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(d);
                    ((DefaultMutableTreeNode) raizz.getChildAt(j)).add(p);
                }
            }
            m.reload();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_Agregar_docenteMouseClicked

    private void agregar_AlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_AlumnosActionPerformed
        try {
            int cuenta = Integer.parseInt(cuenta_Alumno.getText());
            String carrera = carrera_Alumno.getText();
            int acarrera = Integer.parseInt(añosCarrera_Alumnos.getText());
            int clases = Integer.parseInt(clases_Alumno.getText());

            String nombre = nombre_Alumno.getText();
            String apellido = apellido_Alumno.getText();
            String user = user_Alumno.getText();
            String pass = pass_Alumno.getText();

            cuenta_Alumno.setText("");
            carrera_Alumno.setText("");
            añosCarrera_Alumnos.setText("");
            clases_Alumno.setText("");
            nombre_Alumno.setText("");
            apellido_Alumno.setText("");
            user_Alumno.setText("");
            pass_Alumno.setText("");

            persona.add(new Alumnos(cuenta, carrera, acarrera, clases, nombre, apellido, user, pass));
            alumno.add(new Alumnos(cuenta, carrera, acarrera, clases, nombre, apellido, user, pass));
            DefaultTreeModel m = (DefaultTreeModel) jtree_Decano.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            Alumnos a = new Alumnos(cuenta, carrera, acarrera, clases, nombre, apellido, user, pass);
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals("Alumnos")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(a);
                    ((DefaultMutableTreeNode) raiz.getChildAt(j)).add(p);
                }
            }
            m.reload();

            DefaultListModel modelo = (DefaultListModel) jList_Docente.getModel();
            modelo.removeAllElements();
            modelo.addElement(nombre);
            jList_Docente.setModel(modelo);

            DefaultTreeModel c = (DefaultTreeModel) jtree_CEO.getModel();
            DefaultMutableTreeNode raizz = (DefaultMutableTreeNode) c.getRoot();
            for (int j = 0; j < raizz.getChildCount(); j++) {
                if (raizz.getChildAt(j).toString().equals("Alumnos")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(a);
                    ((DefaultMutableTreeNode) raizz.getChildAt(j)).add(p);
                }
            }
            m.reload();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_agregar_AlumnosActionPerformed

    private void crearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearUsuarioMouseClicked
        jd_CrearUsuario.setModal(true);
        jd_CrearUsuario.pack();
        jd_CrearUsuario.setLocationRelativeTo(this);
        jd_CrearUsuario.setVisible(true);
    }//GEN-LAST:event_crearUsuarioMouseClicked

    private void ingresarSistemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarSistemasActionPerformed
        for (int i = 0; i < ceo.size(); i++) {
            if (userMain.getText().equals(ceo.get(i).getUser()) && passMain.getText().equals(ceo.get(i).getPass())) {
                jd_CEO.setModal(true);
                jd_CEO.pack();
                jd_CEO.setLocationRelativeTo(this);
                jd_CEO.setVisible(true);
            }
        }
        for (int i = 0; i < decano.size(); i++) {
            if (userMain.getText().equals(decano.get(i).getUser()) && passMain.getText().equals(decano.get(i).getPass())) {
                jd_decano.setModal(true);
                jd_decano.pack();
                jd_decano.setLocationRelativeTo(this);
                jd_decano.setVisible(true);
            }
        }
        for (int i = 0; i < docente.size(); i++) {
            if (userMain.getText().equals(docente.get(i).getUser()) && passMain.getText().equals(docente.get(i).getPass())) {
                jd_Docente.setModal(true);
                jd_Docente.pack();
                jd_Docente.setLocationRelativeTo(this);
                jd_Docente.setVisible(true);
            }
        }


    }//GEN-LAST:event_ingresarSistemasActionPerformed

    private void jtree_DecanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_DecanoMouseClicked
        // TODO add your handling code here:

        try {
            if (evt.isMetaDown()) {
                Object v1 = jtree_Decano.getSelectionPath().getLastPathComponent();
                nodo_seleccionado = (DefaultMutableTreeNode) v1;
                if (nodo_seleccionado.getUserObject() instanceof Personas) {
                    persona_seleccionada = (Personas) nodo_seleccionado.getUserObject();

                }
            }

            if (evt.isMetaDown()) {

                popup.show(jtree_Decano, evt.getX(), evt.getY());
                int row = jtree_Decano.getClosestRowForLocation(evt.getX(), evt.getY());
                jtree_Decano.setSelectionRow(row);
                Object v1 = jtree_Decano.getSelectionPath().getLastPathComponent();
                nodo_seleccionado = (DefaultMutableTreeNode) v1;

                if (nodo_seleccionado.getUserObject() instanceof Personas) {
                    persona_seleccionada = (Personas) nodo_seleccionado.getUserObject();
                    popup.show(evt.getComponent(),
                            evt.getX(), evt.getY());
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_jtree_DecanoMouseClicked

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jtree_Decano.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_eliminarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed

        try {
            if (persona_seleccionada instanceof Alumnos) {
                Alumnos x = (Alumnos) persona_seleccionada;

                int cuenta = x.getCuenta();
                String carrera = x.getCarrera();
                int acarrera = x.getaCarrera();
                int clases = x.getClases();

                String nombre = x.getNombre();
                String apellido = x.getApellido();
                String user = x.getUser();
                String pass = x.getPass();

                Object[] listar = {nombre, apellido, carrera, cuenta};
                DefaultTableModel modelo = (DefaultTableModel) jt_ListaAlumnos.getModel();
                modelo.addRow(listar);
                jt_ListaAlumnos.setModel(modelo);

                jd_ListarAlumno.setModal(true);
                jd_ListarAlumno.pack();
                jd_ListarAlumno.setLocationRelativeTo(this);
                jd_ListarAlumno.setVisible(true);

            } else if (persona_seleccionada instanceof Docente) {
                Docente x = (Docente) persona_seleccionada;
                String nombre = x.getNombre();
                String apellido = x.getApellido();
                String titulo = x.getPregrado();
                String clase = x.getClase();

                Object[] listar = {nombre, apellido, titulo, clase};
                DefaultTableModel modelo = (DefaultTableModel) jt_ListaDocente.getModel();
                modelo.addRow(listar);
                jt_ListaDocente.setModel(modelo);

                jd_LisarDocente.setModal(true);
                jd_LisarDocente.pack();
                jd_LisarDocente.setLocationRelativeTo(this);
                jd_LisarDocente.setVisible(true);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_ListarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        try {
            if (persona_seleccionada instanceof Alumnos) {
                Alumnos x = (Alumnos) persona_seleccionada;

                String nombre = x.getNombre();
                String apellido = x.getApellido();
                int cuenta = x.getCuenta();
                String carrera = x.getCarrera();
                DefaultListModel modelo = (DefaultListModel) jList_Modificar.getModel();
                modelo.removeAllElements();
                modelo.addElement(nombre);
                modelo.addElement(apellido);
                modelo.addElement(cuenta);
                modelo.addElement(carrera);
                jList_Modificar.setModel(modelo);

                jd_ModificarAlumno.setModal(true);
                jd_ModificarAlumno.pack();
                jd_ModificarAlumno.setLocationRelativeTo(this);
                jd_ModificarAlumno.setVisible(true);

            } else if (persona_seleccionada instanceof Docente) {
                Docente x = (Docente) persona_seleccionada;
                String nombre = x.getNombre();
                String apellido = x.getApellido();
                String titulo = x.getPregrado();
                String clase = x.getClase();

                DefaultListModel modelo = (DefaultListModel) jList_Modificar.getModel();
                modelo.removeAllElements();
                modelo.addElement(nombre);
                modelo.addElement(apellido);
                modelo.addElement(titulo);
                modelo.addElement(clase);

                jList_Modificar.setModel(modelo);

                jd_ModificarAlumno.setModal(true);
                jd_ModificarAlumno.pack();
                jd_ModificarAlumno.setLocationRelativeTo(this);
                jd_ModificarAlumno.setVisible(true);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_modificarActionPerformed

    private void jList_DocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_DocenteMouseClicked

        try {
            if (jList_Docente.getSelectedIndex() >= 0 && evt.getClickCount() == 2) {
                DefaultListModel modelo = (DefaultListModel) jList_Modificar.getModel();
                int po = jList_Modificar.getSelectedIndex();
                if (persona_seleccionada instanceof Alumnos) {
                    Alumnos x = (Alumnos) persona_seleccionada;
                    if (po == 0) {
                        String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
                        x.setNombre(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 1) {
                        String nombre = JOptionPane.showInputDialog("Ingrese el apellido: ");
                        x.setApellido(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 2) {
                        String nombre = JOptionPane.showInputDialog("Ingrese su carrera: ");
                        x.setCarrera(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 3) {
                        int num = Integer.parseInt(JOptionPane.showInputDialog("Ingrese su numero de cuenta: "));
                        x.setCuenta(num);
                        modelo.set(po, num);
                    }
                    DefaultTreeModel m = (DefaultTreeModel) jtree_Decano.getModel();
                    nodo_seleccionado.setUserObject(x);
                    m.reload();

                } else if (persona_seleccionada instanceof Docente) {
                    Docente x = (Docente) persona_seleccionada;
                    if (po == 0) {
                        String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
                        x.setNombre(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 1) {
                        String nombre = JOptionPane.showInputDialog("Ingrese el apellido: ");
                        x.setApellido(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 2) {
                        String nombre = JOptionPane.showInputDialog("Ingrese su Pregrado: ");
                        x.setPregrado(nombre);
                        modelo.set(po, nombre);
                    } else if (po == 3) {
                        String Clase = JOptionPane.showInputDialog("Ingrese su numero de cuenta: ");
                        x.setClase(Clase);
                        modelo.set(po, Clase);
                    }
                    DefaultTreeModel m = (DefaultTreeModel) jtree_Decano.getModel();
                    nodo_seleccionado.setUserObject(x);
                    m.reload();

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_jList_DocenteMouseClicked

    private void jList_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_ModificarMouseClicked

        if (jList_Docente.getSelectedIndex() >= 0 && evt.getClickCount() == 2) {

        }


    }//GEN-LAST:event_jList_ModificarMouseClicked

    private void jtree_CEOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_CEOMouseClicked
        try {
            if (evt.isMetaDown()) {
                Object v1 = jtree_CEO.getSelectionPath().getLastPathComponent();
                nodo_seleccionado = (DefaultMutableTreeNode) v1;
                if (nodo_seleccionado.getUserObject() instanceof Personas) {
                    persona_seleccionada = (Personas) nodo_seleccionado.getUserObject();

                }
            }

            if (evt.isMetaDown()) {

                popup.show(jtree_CEO, evt.getX(), evt.getY());
                int row = jtree_CEO.getClosestRowForLocation(evt.getX(), evt.getY());
                jtree_CEO.setSelectionRow(row);
                Object v1 = jtree_CEO.getSelectionPath().getLastPathComponent();
                nodo_seleccionado = (DefaultMutableTreeNode) v1;

                if (nodo_seleccionado.getUserObject() instanceof Personas) {
                    persona_seleccionada = (Personas) nodo_seleccionado.getUserObject();
                    popup.show(evt.getComponent(),
                            evt.getX(), evt.getY());
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }


    }//GEN-LAST:event_jtree_CEOMouseClicked

    private void Meter_NotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Meter_NotasMouseClicked
        jd_MeterNotas.setModal(true);
        jd_MeterNotas.pack();
        jd_MeterNotas.setLocationRelativeTo(this);
        jd_MeterNotas.setVisible(true);


    }//GEN-LAST:event_Meter_NotasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_docente;
    private javax.swing.JMenuItem Listar;
    private javax.swing.JButton Meter_Notas;
    private javax.swing.JButton agregar_Alumnos;
    private javax.swing.JButton agregar_CEO;
    private javax.swing.JButton agregar_Decano;
    private javax.swing.JSpinner alumnos_Docente;
    private javax.swing.JTextField apellido_Alumno;
    private javax.swing.JTextField apellido_CEO;
    private javax.swing.JTextField apellido_Decano;
    private javax.swing.JTextField apellido_Docentes;
    private javax.swing.JTextField añosCarrera_Alumnos;
    private javax.swing.JTextField carrera_Alumno;
    private javax.swing.JTextField clases_Alumno;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JButton crear_Alumno;
    private javax.swing.JButton crear_CEO;
    private javax.swing.JButton crear_Decano;
    private javax.swing.JButton crear_Docente;
    private javax.swing.JTextField cuenta_Alumno;
    private javax.swing.JTextField descripcion_Docente;
    private javax.swing.JTextField edad_CEO;
    private javax.swing.JTextField edad_Decano;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JTextField experiencia_CEO;
    private javax.swing.JTextField id_CEO;
    private javax.swing.JTextField id_Decano;
    private javax.swing.JButton ingresarSistemas;
    private javax.swing.JButton ingresar_Notas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_Docente;
    private javax.swing.JList<String> jList_Modificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JDialog jd_Alumno;
    private javax.swing.JDialog jd_CEO;
    private javax.swing.JDialog jd_CrearAlumno;
    private javax.swing.JDialog jd_CrearDecano;
    private javax.swing.JDialog jd_CrearDocente;
    private javax.swing.JDialog jd_CrearUsuario;
    private javax.swing.JDialog jd_Docente;
    private javax.swing.JDialog jd_LisarDocente;
    private javax.swing.JDialog jd_ListarAlumno;
    private javax.swing.JDialog jd_MeterNotas;
    private javax.swing.JDialog jd_ModificarAlumno;
    private javax.swing.JDialog jd_crearCEO;
    private javax.swing.JDialog jd_decano;
    private javax.swing.JTable jt_ListaAlumnos;
    private javax.swing.JTable jt_ListaDocente;
    private javax.swing.JTree jtree_CEO;
    private javax.swing.JTree jtree_Decano;
    private javax.swing.JTextField maestria_Decano;
    private javax.swing.JTextField maestria_Docente;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JTextField nombreClase_Docente;
    private javax.swing.JTextField nombre_Alumno;
    private javax.swing.JTextField nombre_CEO;
    private javax.swing.JTextField nombre_Decano;
    private javax.swing.JTextField nombre_Docentes;
    private javax.swing.JTextField nota_Evaluacion;
    private javax.swing.JTextField nota_EvaluacionGeneral;
    private javax.swing.JTextField nota_cooperacion;
    private javax.swing.JTextField nota_participacion;
    private javax.swing.JTextField nota_te;
    private javax.swing.JTextField passMain;
    private javax.swing.JTextField pass_Alumno;
    private javax.swing.JTextField pass_CEO;
    private javax.swing.JTextField pass_Decano;
    private javax.swing.JTextField pass_Docente;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JTextField pregrado_CEO;
    private javax.swing.JTextField pregrado_Decano;
    private javax.swing.JTextField pregrado_Docente;
    private javax.swing.JTextField universitario_Decano;
    private javax.swing.JTextField userMain;
    private javax.swing.JTextField user_Alumno;
    private javax.swing.JTextField user_CEO;
    private javax.swing.JTextField user_Decano;
    private javax.swing.JTextField user_Docente;
    // End of variables declaration//GEN-END:variables
ArrayList<Personas> persona = new ArrayList();
    ArrayList<ceo> ceo = new ArrayList();
    ArrayList<Decano> decano = new ArrayList();
    ArrayList<Docente> docente = new ArrayList();
    ArrayList<Alumnos> alumno = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Personas persona_seleccionada;

}
